manifest:
  remotes:
    - name: github
      url-base: https://github.com

  defaults:
    remote: github
    revision: main

  projects:
    - name: nrf
      remote: github
      repo-path: nrfconnect/sdk-nrf.git
      revision: v2.1.2
      path: nrf
      import: true
    - name: azure-sdk-for-c
      remote: github
      repo-path: dp7hgh7/azure-sdk-for-c.git
      revision: feature/zephyr-support
      path: modules/lib/azure-sdk-for-c

  self:
    path: application
